News app
GlebPilipenko/my-app pull request #11
Opened 2021-02-23 14:45 UTC by GlebPilipenko

news_app - did news_app, adaptive, carousel, .env

2021-02-24 08:14 UTC, alexwerst requested changes

2021-02-24 08:14 UTC, ghost commented on .gitignore
> +.env
add `.env.example` file with 
```
REACT_APP_NEWS_BASE_URL =
REACT_APP_API_KEY = 
```

2021-02-24 08:14 UTC, ghost commented on public/index.html
> +<div data-city="Minsk" data-app="news-widget" data-country="Germany"></div>
I can see the news after removing data-city and data-country...

2021-02-24 08:14 UTC, ghost commented on public/index.html
> +<div data-city="Minsk" data-app="news-widget" data-country="Germany"></div>
We'll need to see news about the city or the country (if there are no news about the city)

2021-02-24 08:14 UTC, ghost commented on public/manifest.json
> +  "icons": [],
?

2021-02-24 08:14 UTC, ghost commented on src/App.tsx
>  import {Weather} from './components/weather/Weather';
![image](https://user-images.githubusercontent.com/15168701/108964340-66f89c00-768c-11eb-8749-dc98967c8cc8.png)

2021-02-24 08:14 UTC, ghost commented on src/api/newsAPI.ts
> +            `everything?q=${city}&pageSize=5&apiKey=${process.env.REACT_APP_API_KEY}`
```
everything?q=${city}&pageSize=5&apiKey=${process.env.REACT_APP_API_KEY}
everything?q=${country}&pageSize=5&apiKey=${process.env.REACT_APP_API_KEY}
```

move to the const with an argument query (city or country)

2021-02-24 08:14 UTC, ghost commented on src/api/newsAPI.ts
> +const instance = axios.create({
```
const newsApi = axios.create({ ... });
const getNewsCity = newsApi.get();
```

2021-02-24 08:14 UTC, ghost commented on src/api/newsAPI.ts
> +type SourceType = {
all types should be at the top of the file or better in the separate file

2021-02-24 08:14 UTC, ghost commented on src/api/weatherAPI.ts
> +    lon: number
`;`

2021-02-24 08:14 UTC, ghost commented on src/components/news/News.tsx
> +    const [state, setState] = useState<NewsAPIType>({
const initialState

2021-03-01 07:35 UTC, aashihmin requested changes

2021-03-01 07:35 UTC, aashihmin commented on src/App.tsx
> +export const App: React.FC<PropsType> = (props) => (
App should return necessary component only (according to the props.app). Leave switch() only

2021-03-01 07:35 UTC, aashihmin commented on src/components/common/errorMessage/ErrorMessage.tsx
> +export const ErrorMessage: React.FC<PropsType> = ({errorMessage}) => {
```
export const ErrorMessage: React.FC<PropsType> = ({errorMessage}) => (
    <div className={style.error__container}>
        <div className={style.error__block}>
            {errorMessage}
        </div>
   </div>
);
```

2021-03-01 07:35 UTC, aashihmin commented on src/utils/GetFormatedDate.ts
> +    return Date.parse(strDate) / 1000;
magic number

2021-03-02 07:06 UTC, aashihmin approved these changes

2021-03-02 07:07 UTC, alexwerst approved these changes

2021-03-02 07:07 UTC, merged