Feat/notes
GlebPilipenko/my-app pull request #12
Opened 2021-03-04 21:30 UTC by GlebPilipenko

notes - refactoring logic, function localStorage.ts in services

2021-03-05 07:54 UTC, alexwerst requested changes

2021-03-05 07:54 UTC, alexwerst commented on package.json
> +    "uuid": "^8.3.2",
fixed version

2021-03-05 07:54 UTC, alexwerst commented on src/index.tsx
> +const ROOT_SELECTORS = ['[data-app="weather-widget"]',
```suggestion
const ROOT_SELECTORS = [
    '[data-app="weather-widget"]',
    '[data-app="news-widget"]',
    '[data-app="notes-widget"]'
];
```

2021-03-05 07:54 UTC, alexwerst commented on src/services/LocalStorage.ts
> +import {NotesType} from '../widget/notes/Notes';
Don't use capital case for services, utils, etc. (LocalStorage.ts -> storage.ts)

2021-03-05 07:54 UTC, alexwerst commented on src/services/LocalStorage.ts
> +    const lsObject = JSON.parse(localStorage.getItem('widget.Notes') || '[]');
What is lsObject? How can I understand that it is a notes object?

2021-03-05 07:54 UTC, alexwerst commented on src/services/LocalStorage.ts
> +export const serviceLocalStorage = (
Your function returns an object - wrong function name! Call it getNotesFromStorage, for example

2021-03-05 07:54 UTC, alexwerst commented on src/services/LocalStorage.ts
> +    newTask?: NotesType, city?: string | undefined, setNotes?: Function) => {
newTask?

2021-03-05 07:54 UTC, alexwerst commented on src/services/LocalStorage.ts
> +};
I think that you need to separate this big service into smaller parts

2021-03-05 07:54 UTC, alexwerst commented on src/widget/notes/Notes.tsx
> +country,
missing tabs

2021-03-05 07:54 UTC, alexwerst commented on src/widget/notes/components/notesForCity/NotesForCity.tsx
> +city,
missing tabs

2021-03-05 07:54 UTC, alexwerst commented on src/widget/notes/components/notesForm/NotesForm.tsx
> +city,
missing tab

2021-03-05 07:54 UTC, alexwerst commented on src/widget/notes/components/notesWithoutCity/NotesWithoutCity.tsx
> +notes,
missing tabs

2021-03-09 08:14 UTC, ghost commented on src/App.tsx
>  enum WidgetTitles {
We can move it to a separate file (src/constants/widget-tiles.ts)

2021-03-09 08:14 UTC, ghost commented on src/services/localStorage.ts
> +export const getParseLocalStorageData = (localStorageName: string) => {
add empty line

2021-03-09 08:14 UTC, ghost commented on src/services/localStorage.ts
> +export const serviceLocalStorage = (localStorageName: string, newNote?: NotesType,
We can set one obj of arguments instead of four arguments
```suggestion
export const serviceLocalStorage = ({
    localStorageName: string,
    newNote?: NotesType,
    city?: string | undefined,
    setNotes?: Function,
}) => {
```

2021-03-09 08:14 UTC, ghost commented on src/services/localStorage.ts
> +                                    city?: string | undefined, setNotes?: Function) => {
You cannot import and use a specific function in shared services. Move this function to the notes service

2021-03-09 08:14 UTC, ghost commented on src/utils/customInputHook.ts
> +import {useState} from 'react';
src/hooks/useInputValue.ts

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +} from './components/accordionWithButtonForm/AccordionCityWithButtonForm';
Please, create index.ts with all imports in the components folder to avoid these long strings

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +    return <FormWithNotes city={city} notes={notes}
```suggestion
    return (
        <FormWithNotes
            city={city}
            notes={notes}
            title={title}
            showForm={showForm}
            addNotes={addNotes}
            cityTitle={cityTitle}
            removeNote={removeNote}
            description={description}
            changeInputValue={changeInputValue}
            changeTxtAreaValue={changeTxtAreaValue}
            changeInputCityValue={changeInputCityValue}
            changeVisibilityForm={changeVisibilityForm}
        />
    );
```

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +    const copyNotes = notes.map(city => city.city);
```suggestion
    const copyNotes = notes.map(({city}) => city);
```

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +        getParseLocalStorageData('widget.Notes'));
'widget.Notes' --> LocalStorageTitles.NotesWidget

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +    let [notes, setNotes] = useState<NotesType[]>(
const?

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +        const findedNotes = serviceLocalStorage(
getNotes() ?

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/Notes.tsx
> +    const copyNotes = notes.map(city => city.city);
useMemo() ?

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/components/notesForm/NotesForm.tsx
> +            {!showForm ? null :
early return!!!

2021-03-09 08:14 UTC, ghost commented on src/widgets/notes/service/getNotes.ts
> +        if (!newNote || !newNote.city) {
```suggestion
        if (!newNote?.city) {
```

2021-03-09 09:09 UTC, ghost commented on src/widgets/notes/components/accordionWithButtonForm/AccordionCityWithButtonForm.tsx
> +                <Button changeVisibilityForm={changeVisibilityForm} />
Add Button to the Form component

2021-03-09 09:09 UTC, ghost commented on src/widgets/notes/components/accordionWithButtonForm/AccordionCityWithButtonForm.tsx
> +                <React.Fragment key={index}>
Create a new AccordionItem component, pls

2021-03-09 09:09 UTC, alexwerst commented on src/widgets/notes/components/notesForCity/NotesForCity.tsx
> +                const title = `• ${obj.title}`;
remove dot

2021-03-09 09:09 UTC, alexwerst commented on src/widgets/notes/components/notesForCity/NotesForCity.tsx
> +            {notes.map((obj: NotesType, index: number) => {
use destructuring

2021-03-09 09:09 UTC, ghost commented on src/widgets/notes/components/notesForCity/NotesForCity.tsx
> +                                    onClick={() => removeNote(title)}>
update removeNote logic, pls

2021-03-14 06:43 UTC, aashihmin commented on src/App.tsx
> +import {Weather} from './widgets';
```suggestion
import {News, Notes, Weather} from './widgets';
```

2021-03-14 06:43 UTC, aashihmin commented on src/enums/index.ts
> +export {WidgetTitles} from './enum';
create one index ts in the enums folder and remove enum ts

2021-03-14 06:43 UTC, aashihmin commented on src/typings/index.ts
> +import {WidgetTitles} from "src/enums";
single quoters

2021-03-14 06:43 UTC, aashihmin commented on src/utils/getLowerCaseString.ts
> +    if (!value) {
you need to do checks out of this function. this simple function should always return a string in a lower case

2021-03-14 06:43 UTC, aashihmin commented on src/widgets/news/News.tsx
> +import {getFormatedDate, getDateToTimeStamp} from '../../utils/getFormatedDate';
```suggestion
import {getFormatedDate, getDateToTimeStamp} from 'src/utils';
```

2021-03-14 06:43 UTC, aashihmin commented on src/widgets/weather/components/informationOfCity/InformationOfCity.tsx
> +import {getFormatedDate} from '../../../../utils/getFormatedDate';
```suggestion
import {getFormatedDate} from 'src/utils';
```

2021-03-14 06:43 UTC, aashihmin commented on tsconfig.json
> +    "baseUrl": ".",
```suggestion
    "baseUrl": "./",    
    "paths": {
      "~/*": ["src/*"]
    }
```
Example: 
```
   ... from '../../../../smth'
```
```   
   vs
    ... from '~/smth'
```

2021-03-23 06:55 UTC, aashihmin approved these changes

2021-03-23 06:56 UTC, alexwerst approved these changes

2021-03-23 06:56 UTC, merged