Feat/covid app
GlebPilipenko/my-app pull request #13
Opened 2021-03-24 07:27 UTC by GlebPilipenko

2021-03-29 07:36 UTC, aashihmin commented on src/utils/getFormattedDate.ts
> +    const date = new Date(+dt * oneThousand);
?

2021-03-29 07:36 UTC, aashihmin commented on src/widgets/covid/CovidDiagram.tsx
> +export const CovidDiagram: FC<PropsType> = ({country = 'invalid_country'}) => {
strange default value

2021-03-29 07:36 UTC, aashihmin commented on src/widgets/covid/CovidDiagram.tsx
> +  if (state.length > 200) {
What does it mean?

2021-04-09 06:22 UTC, aashihmin requested changes

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/enum/index.ts
> +export enum ArrayLength {
Delete this file

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/components/svgDiagrams/SVGDiagrams.tsx
> +  const [, , , cases, , deaths, , recovered, , active] = state;
???

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/CovidDiagram.tsx
> +  const [state, setState] = useState<any | CovidAPIType[]>(null);
Why do we need any type?

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/CovidDiagram.tsx
> +        setState(Object.entries(infoByCovid.data));
???
```suggestion
        if (infoByCovid?.data) {
          const { cases, deaths, recovered, active } = infoByCovid.data;
          setState({ cases, deaths, recovered, active });
        }
```
or smth like this

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/CovidDiagram.tsx
> +  if (state.length >= numCountriesInWorld) {
strange check..

2021-04-09 06:22 UTC, aashihmin commented on src/widgets/covid/components/svgDiagrams/typings/index.ts
> +  state: any | CovidAPIType;
type any

2021-04-21 06:43 UTC, aashihmin approved these changes

2021-04-21 06:44 UTC, alexwerst approved these changes

2021-04-21 06:44 UTC, merged